[package]
name = "fastpfor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Safe interop between Rust and C++
cxx = "1.0.79"

